### ISSUE TITLE
Setup Apollo GraphQL IDE plugin

### ISSUE THREAD

**Issue by duongdev** [targeek/guru-erp#48]
Follow [this guide](https://www.apollographql.com/docs/platform/editor-plugins.html)

**Comment by duongdev** [comment]
I am getting errors when trying to setup this plugin. The errors look like:

```Error: Type "Account" already exists in the schema. It cannot also be defined in this type definition.

Field "Account.id" already exists in the schema. It cannot also be defined in this type extension.

Field "Account.email" already exists in the schema. It cannot also be defined in this type extension.

Field "Account.avatar" already exists in the schema. It cannot also be defined in this type extension.

Type "Empty" already exists in the schema. It cannot also be defined in this type definition.

Type "Date" already exists in the schema. It cannot also be defined in this type definition.

Type "JSON" already exists in the schema. It cannot also be defined in this type definition.
    at assertValidSDLExtension (/Users/duongdev/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/graphql/validation/validate.js:106:11)
    at Object.extendSchema (/Users/duongdev/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/graphql/utilities/extendSchema.js:63:43)
    at loadingHandler.handle (/Users/duongdev/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/apollo-language-server/lib/project/client.js:81:37)```

Guys someone pls help me on this issue.

**Comment by duongdev** [comment]
ping @nguyenthienthanh could you help me on this issue?
